post_install() {
    echo -e "\n** The files have been installed in /boot/grub/themes/radar **\n"
    sed -i "s/Vimix/radar/g" /etc/default/grub
    grub-mkconfig -o /boot/grub/grub.cfg
}

post_upgrade() {
    post_install
}

post_remove() {
    echo -e "\n** We change the theme back to the default vimix theme **\n"
    sed -i "s/radar/Vimix/g" /etc/default/grub
    grub-mkconfig -o /boot/grub/grub.cfg  
}
